# Generated by Django 5.0.1 on 2024-01-29 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.IntegerField(null=True, verbose_name='Centro De Costo')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Arrendado', 'Arrendado'), ('En Mantenimiento', 'En Mantenimiento'), ('Siniestrado', 'Siniestrado'), ('En Revisión', 'En Revisión')], default='Disponible', max_length=50, verbose_name='Estado')),
                ('ppu', models.CharField(default='AAAA-00', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de PPU no válido. Ejemplo: ABCD-18', regex='^[A-Z]{4}-[0-9]{2}$')], verbose_name='PPU')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('vin', models.CharField(max_length=255, verbose_name='VIN')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('numero_motor', models.IntegerField(blank=True, null=True, verbose_name='Número De Motor')),
                ('flota', models.CharField(choices=[('ALJIBE', 'ALJIBE'), ('SUPERSUCKER', 'SUPERSUCKER')], default='none', max_length=50, verbose_name='Flota')),
            ],
        ),
    ]
