# Generated by Django 5.0.1 on 2024-02-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Correctivo', max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.camion')),
            ],
        ),
    ]
